### ISSUE TITLE
Linking fails against libssl on OS X

### ISSUE THREAD

**Issue by habnabit** [pingcap/grpc-rs#330] opened 2019-06-12 18:04 UTC
**Describe the bug**
I found this originally on another project, but I can reproduce the same thing against the `grpc-rs` repo. The final step of `cargo build` fails with a linker error:

```
[...]
  = note: ld: warning: directory not found for option '-L/Users/habnabit/Projects/20181023-activity-aggregator/grpc-rs/target/debug/build/grpcio-sys-88e0b97a2cd094d1/out/build/third_party/boringssl/ssl'
          ld: warning: directory not found for option '-L/Users/habnabit/Projects/20181023-activity-aggregator/grpc-rs/target/debug/build/grpcio-sys-88e0b97a2cd094d1/out/build/third_party/boringssl/crypto'
          ld: library not found for -lssl
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Full output here: https://gist.github.com/habnabit/1b9a0cf0d0454db3ee98e7bb46f40624

**To Reproduce**
On a clean `grpc-rs` checkout:

```
$ git checkout v0.4.4
$ git submodule update --init --recursive
$ OPENSSL_ROOT_DIR=/usr/local/opt/openssl cargo build --features openssl --examples
```

**Expected behavior**
Presumably this build should succeed. I don't think I have a broken openssl.

**System information**
macOS 10.14.5; homebrew openssl.
```
$ cargo version
cargo 1.35.0 (6f3e9c367 2019-04-04)
$ rustc --version
rustc 1.35.0 (3c235d560 2019-05-20)
$ ls -ld /usr/local/opt/openssl
lrwxr-xr-x  1 habnabit  admin  24 May 31 20:26 /usr/local/opt/openssl -> ../Cellar/openssl/1.0.2r
```

**Comment by habnabit** [comment] 2019-06-12 18:09
I did check and I was running against 93e45e59aba40b10e04e04814073baa75a082e36 and it fails in the same way against ce8139d033fdd95c6a74a09dadb144869ef07e01.

**Comment by aknuds1** [comment] 2019-07-31 13:28
I can't build my package depending on the grpcio crate, version 0.5.0-alpha1, on OS X, if I enable the "openssl" feature. I enabled the openssl feature in the first place, because I couldn't get it to build on Linux because the reqwest dependency tried to link against openssl.

**Comment by BusyJay** [comment] 2019-08-01 10:34
@aknuds1 Can you paste the error here?

**Comment by aknuds1** [comment] 2019-08-01 11:35
@BusyJay I think the following is the main error, if you need I can paste the whole error block:

```
= note: ld: warning: directory not found for option '-L/Users/arve/Projects/<project>/target/debug/build/grpcio-sys-3625ee377aa885e0/out/build/third_party/boringssl/ssl'
          ld: warning: directory not found for option '-L/Users/arve/Projects/<project>/target/debug/build/grpcio-sys-3625ee377aa885e0/out/build/third_party/boringssl/crypto'
          ld: library not found for -lssl
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by BusyJay** [comment] 2019-08-01 11:53
Have you install openssl library? Can it compile if you just use reqwest? Note that grpcio also requires devel files of openssl. And you may try vendored feature if you like.

**Comment by aknuds1** [comment] 2019-08-01 12:20
@BusyJay I've installed openssl via Homebrew, and I can build another project which uses reqwest (and not grpcio).

How do I use the vendored feature?

**Comment by BusyJay** [comment] 2019-08-01 12:54
Just enable the features like following:
```
[dependencies]
grpcio = { version = "0.4.4", features = ["openssl-vendored"] }
```
It will compile openssl from source.

**Comment by aknuds1** [comment] 2019-08-01 13:51
> Just enable the features like following:
> 
> ```
> [dependencies]
> grpcio = { version = "0.4.4", features = ["openssl-vendored"] }
> ```
> 
> It will compile openssl from source.

@BusyJay Great, thanks for the tip! I'll try it.

**Comment by habnabit** [comment] 2019-08-01 13:58
My system already has libssl and it’s already being linked to from other
rust code. Do I have to vendor libssl for grpcio?

**Comment by aknuds1** [comment] 2019-08-01 14:06
@BusyJay Version 0.5.0-alpha.1 doesn't have the feature "openssl-vendored". Has it made its way into the 0.5 release branch?

I can't yet use the latest 0.5.0 alpha, since I got build errors trying to upgrade.

**Comment by BusyJay** [comment] 2019-08-01 16:06
@habnabit Technically you don't. The error is reported because ld can't find the library. Another way to fix this is tell ld where the openssl library locates. You can add the libssl path to the LIBRARY_PATH/LD_LIBRARY_PATH if you are using Linux. There should be similar variables on MacOS too.

@aknuds1 I think it has been included in 0.5.0-alpha.2.

**Comment by habnabit** [comment] 2019-08-01 20:52
@BusyJay if `OPENSSL_ROOT_DIR=/usr/local/opt/openssl` isn't sufficient for that, I'm not sure why that environment variable is required at all. I'll test with the latest commits.

**Comment by BusyJay** [comment] 2019-08-02 03:48
@habnabit The variables is used for cmake, which should be enough for most case. However I don't have a mac environment to test what can go wrong, but at lease it works for travis OSX build.

**Comment by habnabit** [comment] 2019-08-03 10:00
@BusyJay on a2f14a2b108a33e2200531f617733563ecee837c I can't figure out how to build `tests-and-examples` now that it's a workspace thing. How can I do a build of "everything in this crate, including examples" like in my original post?

**Comment by aknuds1** [comment] 2019-08-03 21:09
Update: I tried to build a project depending on grpcio 0.5.0-alpha.3 with feature openssl enabled, it fails to link: 

```
  = note: ld: warning: directory not found for option '-L/Users/arve/Projects/grpc-rs-example/target/debug/build/grpcio-sys-437c049903f5185c/out/build/third_party/boringssl/ssl'
          ld: warning: directory not found for option '-L/Users/arve/Projects/grpc-rs-example/target/debug/build/grpcio-sys-437c049903f5185c/out/build/third_party/boringssl/crypto'
          ld: library not found for -lssl
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

See [this gist](https://gist.github.com/aknuds1/7a749b5a04c3fa3891cf9546161088d7) for full error output.

**Comment by Hoverbear** [comment] 2019-09-30 18:34
Hi folks, is this still an issue? Can we close it?

**Comment by habnabit** [comment] 2019-09-30 18:36
I haven't tried to build anything again in the last few days, but unless there's been any changes to specifically address this issue, I doubt it's been resolved. I won't have a free moment to try it again myself probably for a few days.

**Comment by aknuds1** [comment] 2019-09-30 20:37
@hoverbear I can try when time allows

**Comment by aknuds1** [comment] 2019-10-01 21:11
@Hoverbear I get the same build error as before when trying.

**Comment by Hoverbear** [comment] 2019-10-02 16:43
Dangit. :(

**Comment by BusyJay** [comment] 2019-10-03 07:06
@Hoverbear @nrc Do you have Mac books? Would you like to try and fix it? I guess there are differences between the CI environment and a true MacOS.

**Comment by aknuds1** [comment] 2019-10-03 07:22
@BusyJay I could try to fix it?

**Comment by BusyJay** [comment] 2019-10-03 08:06
Sure, thanks for your help!

**Comment by aknuds1** [comment] 2019-10-03 08:09
@BusyJay Do you have any tips on how to fix the issue? I don't really know where to start.

**Comment by BusyJay** [comment] 2019-10-03 08:27
I think you can do a full rebuild and then check where the ssl library and crypto library locates. They are expected to be built and written to `target/debug/build/grpcio-sys-hashes/out/build/third_party/boringssl/ssl`.

**Comment by habnabit** [comment] 2019-10-03 08:31
[I asked earlier](https://github.com/pingcap/grpc-rs/issues/330#issuecomment-517912641) about how to build the examples, which seems relevant again. I can put together a minimal example crate but probably you want building the examples to succeed out of the box.

**Comment by aknuds1** [comment] 2019-10-03 08:34
@habnabit I have a small example already which reproduces the error.

**Comment by aknuds1** [comment] 2019-10-03 08:34
> I think you can do a full rebuild and then check where the ssl library and crypto library locates. They are expected to be built and written to `target/debug/build/grpcio-sys-hashes/out/build/third_party/boringssl/ssl`.

@BusyJay Thanks! Hopefully this'll be enough to get me going.

**Comment by BusyJay** [comment] 2019-10-03 08:36
@habnabit Sorry I missed the question. `cargo build --all` should build all these things. Or you can use `cargo build -p tests-and-examples`.

**Comment by habnabit** [comment] 2019-10-03 08:59
@BusyJay thanks. Confirmed it fails the same way on 019e1767d1c8317344987e05ee6876efa6f26c6f: https://gist.github.com/habnabit/5661b94e5ba9dbdb8a315283b59967d4

```
$ cargo version
cargo 1.38.0 (23ef9a4ef 2019-08-20)
$ rustc --version
rustc 1.38.0 (625451e37 2019-09-23)
$ ls -ld /usr/local/opt/openssl
lrwxr-xr-x  1 habnabit  admin  24 Oct  3 09:39 /usr/local/opt/openssl -> ../Cellar/openssl/1.0.2t
```

**Comment by Hoverbear** [comment] 2019-10-03 14:26
@BusyJay Sadly I am Windows/Linux :( I remember when working with openssl on Mac `pkg-config` becomes useful?

**Comment by nrc** [comment] 2019-10-07 02:52
I'm on Mac. Let me know if you want me to test anything out (I'm afraid I don't know much about ld, so I'm probably not the best person to fix this).

**Comment by BusyJay** [comment] 2019-10-21 11:57
Hi, @habnabit @aknuds1 I recently got a chance to tweak around on a mac and made up a fix. Can you verify whether #387 fixes your issues?

**Comment by aknuds1** [comment] 2019-10-21 21:51
@BusyJay I can confirm your fix is good!

**Closed** 2019-10-22 05:28 UTC
